trigger: none

pool: Default

stages:
- stage: terraform
  jobs:
  - job: terraform
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
- stage: Terraforminit
  jobs:
  - job: Terraforminit
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'
        backendServiceArm: 'connection2'
        backendAzureRmResourceGroupName: 'rg-lab'
        backendAzureRmStorageAccountName: 'duedatelab'
        backendAzureRmContainerName: 'pipelinetfstate'
        backendAzureRmKey: 'terraform.tfstate'
- stage: terraformplan
  jobs:
  - job: terraformplan
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'
        environmentServiceNameAzureRM: 'sc-pipeline'
- stage: terraformapply
  jobs:
  - job: terraformapply
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'
        environmentServiceNameAzureRM: 'sc-pipeline'