trigger: none

pool: Default

stages:
- stage: TerraformInit
  jobs:
  - job: TerraformInit
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)Networking/Lab2'
        backendServiceArm: 'connection2'
        backendAzureRmResourceGroupName: 'rg-lab'
        backendAzureRmStorageAccountName: 'duedatelab'
        backendAzureRmContainerName: 'pipelinetfstate'
        backendAzureRmKey: 'pipeline.tfstate'
- stage: TerraformValidate
  jobs:
  - job: TerraformValidate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'
- stage: TerraformPlan
  jobs:
  - job: TerraformPlan
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)Networking/Lab2'
        environmentServiceNameAzureRM: 'connection2'
- stage: TerraformApply
  jobs:
  - job: TerraformApply
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)Networking/Lab2'
        environmentServiceNameAzureRM: 'connection2'
