trigger: none

pool:
  vmimage = ubuntu-latest

stages:
- stage: Environment test stage
  jobs:
  - deployment: dev
    displayName: Dev
    environment: frontend-dev
    strategy:
      runOnce:
        steps: 
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'test'
            targetPath: '$(Pipeline.Workspace)'