trigger: none

pool: Default

stages:
- stage: terraforminstaller
  displayName: terraforminstaller
  jobs:
  - job: terraforminstaller
    displayName: terraforminstaller
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
- stage: Terraforminit
  displayName: Terraform Init
  jobs:
  - job: terraforminit
    displayName: Terraform Init
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Basic/Lab2'
        backendServiceArm: 'sc-pipeline'
        backendAzureRmResourceGroupName: 'rg-pipeline'
        backendAzureRmStorageAccountName: 'storagecontainerlab'
        backendAzureRmContainerName: 'tfstate-container'
        backendAzureRmKey: 'terraform.tfstate'