trigger: none

pool: 
  vmimage: "ubuntu-latest"

stages:
- stage: Terraforminit
  jobs:
  - job: Terraforminit
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'
- stage: Terraformvalidate
  jobs:
  - job: Terraformvalidate
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Networking/Lab2'


